# Generated by Django 5.2.9 on 2025-12-09 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employ', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='phone_number',
            new_name='number',
        ),
    ]
